project:
  type: website

website:
  title: "JDemetra+ Universe Blog"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/jdemetra
format:
  html:
    theme: 
      - custom.scss
      - cosmo

editor: source

comments:
  giscus:
    repo: annasmyk/JD_Quarto_Blog
